services:

  # Request decoders
  DigitalCraftsman\CQRS\RequestDecoder\JsonRequestDecoder:
    autowire: true
    autoconfigure: true
    tags: [ 'cqrs.request_decoder' ]

  # DTO constructors
  DigitalCraftsman\CQRS\DTOConstructor\SerializerDTOConstructor:
    autowire: true
    autoconfigure: true
    tags: [ 'cqrs.dto_constructor' ]

  # Response constructors
  DigitalCraftsman\CQRS\ResponseConstructor\EmptyJsonResponseConstructor:
    autowire: true
    autoconfigure: true
    tags: [ 'cqrs.response_constructor' ]

  DigitalCraftsman\CQRS\ResponseConstructor\EmptyResponseConstructor:
    autowire: true
    autoconfigure: true
    tags: [ 'cqrs.response_constructor' ]

  DigitalCraftsman\CQRS\ResponseConstructor\SerializerJsonResponseConstructor:
    autowire: true
    autoconfigure: true
    tags: [ 'cqrs.response_constructor' ]

  DigitalCraftsman\CQRS\ResponseConstructor\StreamedResponseConstructor:
    autowire: true
    autoconfigure: true
    tags: [ 'cqrs.response_constructor' ]

  # Service map
  DigitalCraftsman\CQRS\ServiceMap\ServiceMap:
    arguments:
      $requestValidators: !tagged_locator cqrs.request_validator
      $requestDecoders: !tagged_locator cqrs.request_decoder
      $requestDataTransformers: !tagged_locator cqrs.request_data_transformer
      $dtoConstructors: !tagged_locator cqrs.dto_constructor
      $dtoValidators: !tagged_locator cqrs.dto_validator
      $handlerWrappers: !tagged_locator cqrs.handler_wrapper
      $commandHandlers: !tagged_locator cqrs.command_handler
      $queryHandlers: !tagged_locator cqrs.query_handler
      $responseConstructors: !tagged_locator cqrs.response_constructor

  # Controllers
  DigitalCraftsman\CQRS\Controller\CommandController:
    autoconfigure: true
    autowire: true
    arguments:
      $defaultRequestValidatorClasses: '%cqrs.command_controller.default_request_validator_classes%'
      $defaultRequestDecoderClass: '%cqrs.command_controller.default_request_decoder_class%'
      $defaultRequestDataTransformerClasses: '%cqrs.command_controller.default_request_data_transformer_classes%'
      $defaultDTOConstructorClass: '%cqrs.command_controller.default_dto_constructor_class%'
      $defaultDTOValidatorClasses: '%cqrs.command_controller.default_dto_validator_classes%'
      $defaultHandlerWrapperClasses: '%cqrs.command_controller.default_handler_wrapper_classes%'
      $defaultResponseConstructorClass: '%cqrs.command_controller.default_response_constructor_class%'
    tags: [ 'controller.service_arguments' ]

  DigitalCraftsman\CQRS\Controller\QueryController:
    autoconfigure: true
    autowire: true
    arguments:
      $defaultRequestValidatorClasses: '%cqrs.command_controller.default_request_validator_classes%'
      $defaultRequestDecoderClass: '%cqrs.query_controller.default_request_decoder_class%'
      $defaultRequestDataTransformerClasses: '%cqrs.query_controller.default_request_data_transformer_classes%'
      $defaultDTOConstructorClass: '%cqrs.query_controller.default_dto_constructor_class%'
      $defaultDTOValidatorClasses: '%cqrs.query_controller.default_dto_validator_classes%'
      $defaultHandlerWrapperClasses: '%cqrs.query_controller.default_handler_wrapper_classes%'
      $defaultResponseConstructorClass: '%cqrs.query_controller.default_response_constructor_class%'
    tags: [ 'controller.service_arguments' ]
